databases:
  - name: gitea
    plan: starter

services:
  - type: web
    name: my site
    env: static
    branch: master
    buildCommand: cd ./www.mackenzieclark.codes && hugo --gc --minify
    staticPublishPath: ./www.mackenzieclark.codes/public
  - type: web
    name: pomo
    env: static
    repo: https://github.com/xmclark/pomoday-v2.git
    branch: master
    buildCommand: npm install && npm run dist
    staticPublishPath: dist
    domains:
      - pomo.mackenzieclark.codes
  - type: web
    name: gitea
    env: docker
    repo: https://github.com/go-gitea/gitea.git
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    domains:
      - gitea.mackenzieclark.codes
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: DB_USER
        fromDatabase:
          name: gitea
          property: user
      - key: DB_PASSWD
        fromDatabase:
          name: gitea
          property: password
      - key: DB_NAME
        fromDatabase:
          name: gitea
          property: database
      - key: DB_HOST
        fromDatabase:
          name: gitea
          property: host
      - key: DB_TYPE
        value: postgres
      - key: USER_UID
        value: 1000
      - key: USER_GID
        value: 1000
      - key: ROOT_URL
        value: https://gitea.mackenzieclark.codes
      - key: RUN_MODE
        value: prod
      - key: SECRET_KEY
        sync: false
